### ISSUE TITLE
DateEntry doesn't play well with Entry textvariable.

### ISSUE THREAD

**Issue by dmalves** [israel-dryer/ttkbootstrap#177]
Hi,
I use a custom date entry on my project that uses DateEntry:

-----------------------------------------------
```
def entrada_calendário(
    master,
    label: str,
    variável: StringVar,
    labelCase: bool = True,
    tip: str = None,
    tip_largura: int = None,
    habilitado: bool = True,
):
    """
    Cria uma entrada de data usando calendário.

    Parâmetros:
        master(widget): um widget container.

        label(str): texto para o label widget.

        variável(StringVar): valor de entrada do calendário.

        labelCase(bool): se verdadeiro muda o 'case' do label
                         usando a função title().

        tip(str): texto para o ToolTip.

        tip_largura(int): largura em pixels do texto ToolTip. None usa
                          largura padrão.

        habilitado(bool): determina se widget está habilitado.
    """
    container = ttk.Frame(master)
    container.pack(
        fill=X,
        expand=YES,
        pady=5,
    )
    if labelCase:
        texto = label.title()
    else:
        texto = label

    lbl = ttk.Label(master=container, text=texto, width=10)
    lbl.pack(side=LEFT, padx=5)

    dataEntry = DateEntry(
        master=container,
        dateformat=r"%d-%m-%Y",
    )
    dataEntry.pack()

    # variável contendo a data selecionada no calendário
    dataEntry.entry.configure(textvariable=variável)

    return dataEntry

```
--------------------------------------------

Look this line:
`    dataEntry.entry.configure(textvariable=variável)
`
I used textvariable from internal Entry of DateEntry widget.

How do I use my custom widget?

-------------------------------
```
self.data = tk.StringVar()
entrada_calendário(
    master=lblFrame,
    label="aniversário",
    variável=self.data,   
    tip="Data de aniversário do proprietário.",
)
```
-------------------------------

the variable self.data is pointing to the textvariable configured on my custom widget:

    dataEntry.entry.configure(textvariable=variável)

The widget shows just fine:

![image](https://user-images.githubusercontent.com/5115787/152222374-f6525919-de2e-42f5-8108-c4285af617b8.png)

Look that the Entry is empty as expected. If I push the button I get the following error:
```

ate entry text does not match %d-%m-%Y
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/daniel/.pyenv/versions/3.9.0/lib/python3.9/tkinter/__init__.py", line 1885, in __call__
    return self.func(*args)
  File "/home/daniel/.pyenv/versions/3.9.0/envs/mysystem/lib/python3.9/site-packages/ttkbootstrap/widgets.py", line 238, in _on_date_ask
    old_date = datetime.strptime(_val or self._startdate, self._dateformat)
TypeError: strptime() argument 1 must be str, not datetime.datetime

```

There is a working around. I just set the StringVar with a valid data:
```

self.data = tk.StringVar()
self.data.set(r"2-2-2022")   # WORKING AROUND
entrada_calendário(
    master=lblFrame,
    label="aniversário",
    variável=self.data,
    tip="Data de aniversário do proprietário.",
)

```
I am not sure if this is a bug or an expected behavior. Anyway, maybe it is not a bad idea to expose a textvariable parameter option on widgets where you expect to get a value back. On my opinion, it would be more  transparent to the user. The user would not need to know anything about the internal parts (Entry/Button). Also, DateEntry could have some sort of callback command when date is selected.

I hope this helps on the design of the widgets.

**Comment by dmalves** [comment]
This working around is more dynamic:

```
self.data = tk.StringVar()
data = date.today()
data = f"{data.day}-{data.month}-{data.year}"
self.data.set(data)
entrada_calendário(
    master=lblFrame,
    label="aniversário",
    variável=self.data,
    tip="Data de aniversário do proprietário.",
)
```

**Comment by dmalves** [comment]
Ok, I visited widgets.py and it looks like it is an expected behavior considering that textvariable on Entry widget .

from widgets.py line 225

```
def _on_date_ask(self):
        """Callback for pushing the date button"""
        _val = self.entry.get()
        try:
            self._startdate = datetime.strptime(_val, self._dateformat)
        except Exception as e:
            print("Date entry text does not match", self._dateformat)
            self._startdate = datetime.today()
            self.entry.delete(first=0, last=tk.END)
            self.entry.insert(
                tk.END, self._startdate.strftime(self._dateformat)
            )

```

 _val = self.entry.get() produces an empty value because textvariable is empty. If I set textvariable to an expected date format it works just fine.

**Comment by dmalves** [comment]
I tried something different, If I set the textvariable of the internal Entry widget empty and set a startdate. The startdate shows EMPTY. So, the textvariable overwrite any default behavior of the startdate.

**Comment by israel-dryer** [comment]
here is a working example

```python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *

root = ttk.Window()

# create variable to store date with default value
var = ttk.Variable(value='2-2-2022')

def get_date_from_widget():
    date = var.get()
    print(date)

frame = ttk.Frame(root, padding=10)
frame.pack(padx=10, pady=10)

de = ttk.DateEntry(frame, dateformat="%d-%m-%Y")
de.entry.configure(textvariable=var)
de.pack(fill=X)

btn = ttk.Button(frame, text='Print Date', command=get_date_from_widget)
btn.pack(padx=10, pady=10)

root.mainloop()
```

![image](https://user-images.githubusercontent.com/42584742/152243648-5d45f93a-d49c-4433-b7e3-0edcedb6d601.png)
