### ISSUE TITLE
Checkbutton: UnboundLocalError: local variable 'fnt' referenced before assignment

### ISSUE THREAD

**Issue by bcyran** [israel-dryer/ttkbootstrap#234]
### Desktop (please complete the following information):

ttkbootstrap version: 1.7.3
OS: Arch Linux
Python version: 3.10.2

### Describe the bug

`Checkbutton` with default style causes an exception:
```
Traceback (most recent call last):
  File "/home/bazyli/Kod/test.py", line 7, in <module>
    checkbox = ttk.Checkbutton(root, text="checkbox")
  File "/home/bazyli/Kod/tmp/lib/python3.10/site-packages/ttkbootstrap/style.py", line 4869, in __init__
    ttkstyle = Bootstyle.update_ttk_widget_style(
  File "/home/bazyli/Kod/tmp/lib/python3.10/site-packages/ttkbootstrap/style.py", line 4955, in update_ttk_widget_style
    builder_method(builder, widget_color)
  File "/home/bazyli/Kod/tmp/lib/python3.10/site-packages/ttkbootstrap/style.py", line 3987, in create_checkbutton_style
    images = self.create_checkbutton_assets(colorname)
  File "/home/bazyli/Kod/tmp/lib/python3.10/site-packages/ttkbootstrap/style.py", line 4132, in create_checkbutton_assets
    draw.text((20, font_offset), indicator, font=fnt, fill=check_color)
UnboundLocalError: local variable 'fnt' referenced before assignment
```
Any other style works fine.

### To Reproduce

Run:
```python
import tkinter as tk

import ttkbootstrap as ttk

root = tk.Tk()

checkbox = ttk.Checkbutton(root, text="checkbox")
checkbox.pack()

root.mainloop()
```

**Comment by israel-dryer** [comment]
Is this the "lite" version of Arch Linux? If so, it is probably missing the standard fonts package. If you look in my style module where this font is being used, I'm trying to identify an os specific font that is valid. If you can identify one that I can use with that Linux distro, I will add it to the logic.

**Comment by israel-dryer** [comment]
Yes, it should be 
```python
fnt = ImageFont.load_default()
```
I'll make that update. Thanks!
