### ISSUE TITLE
 _on_date_ask strange exception on empty DateEntry

### ISSUE THREAD

**Issue by dmalves** [israel-dryer/ttkbootstrap#372]
### Desktop (please complete the following information):

ttkbootstrap: 1.9.0
OS: Linux 64 bits
python: 3.10.7

### Describe the bug

When DateEntry is empty, if I try to click on calendar button, I get the following error:

```python
Date entry text does not match %x
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/user/.pyenv/versions/3.10.7/envs/financeiro_3.10.7/lib/python3.10/site-packages/ttkbootstrap/widgets.py", line 239, in _on_date_ask
    old_date = datetime.strptime(_val or self._startdate, self._dateformat)
TypeError: strptime() argument 1 must be str, not datetime.datetime
```

### Expected behavior

If DateEntry is empty, it should ask for date silently.

### Additional context

The error is on line 239 (widgets.py)
```python
old_date = datetime.strptime(_val or self._startdate, self._dateformat)
```
If DateEntry is empty an exception occurs and the following line executes:

```python
self._startdate = datetime.today()
```
my guess is that it should be converted to string.

My use case is simple. When my user selects a combobox I have to erase DateEntry content. So if the user clicks on calendar it gets the described error. Could the empty string case do not generate an exception? Or could be a way to catch this exception?

**Comment by dmalves** [comment]
Possible fix. Not tested yet. Just two line.

```python
def _on_date_ask(self):
        """Callback for pushing the date button"""
        # FIX: clean white space (always a good idea).
        _val = self.entry.get().strip()
        #_val = self.entry.get()
        try:
            self._startdate = datetime.strptime(_val, self._dateformat)
        except Exception as e:
            print("Date entry text does not match", self._dateformat)
            self._startdate = datetime.today()
            self.entry.delete(first=0, last=tk.END)
            self.entry.insert(
                tk.END, self._startdate.strftime(self._dateformat)
            )
        # FIX: datetime.strptime needs str as first arg
        old_date = datetime.strptime(_val or self._startdate.strftime(self._dateformat), self._dateformat)
        #old_date = datetime.strptime(_val or self._startdate, self._dateformat)

        # get the new date and insert into the entry
        new_date = Querybox.get_date(
            parent=self.entry,
            startdate=old_date,
            firstweekday=self._firstweekday,
            bootstyle=self._bootstyle,
        )
        self.entry.delete(first=0, last=tk.END)
        self.entry.insert(tk.END, new_date.strftime(self._dateformat))
        self.entry.focus_force()
```

**Comment by dmalves** [comment]
For those experiencing this problem, on version 1.9.0, here is a quick workaround while there is not a version upgrade:

```python
def _fix_ttkbootstrap_dentry(dentry: ttk.DateEntry):
    """
    Quick workaround for ttkbootstrap bug:
        * https://github.com/israel-dryer/ttkbootstrap/issues/372
    """

    def _empty_entry():

        _val = dentry.entry.get().strip()
        if not _val:
            # entry is string, fix it by inserting today's date
            dentry._startdate = datetime.today()
            dentry.entry.delete(first=0, last=tk.END)
            dentry.entry.insert(tk.END, dentry._startdate.strftime(dentry._dateformat))

            # call original button callback
            dentry._on_date_ask()

    # change button callback
    dentry.button.configure(
        command=_empty_entry,
    )
```

Just pass a DateEntry to  _fix_ttkbootstrap_dentry function  like this:
```python
mydentry = ttk.DateEntry(master=self)
mydentry.pack()

# applying workaround
 _fix_ttkbootstrap_dentry(mydentry)

```
