### ISSUE TITLE
Messagebox exception when using inherited window

### ISSUE THREAD

**Issue by bison--** [israel-dryer/ttkbootstrap#403]
### Desktop (please complete the following information):

ttkbootstrap Version: 1.10.0
OS: Windows 10 19045.2364
Python Version: User Current Version:- 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

### Describe the bug

When calling a `Messagebox` when using an inherited window class, it shows an empty window and outputs an error to the command line.

```python
Messagebox.show_warning('TEST MESSAGE', title='TEST TITLE')
```

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\saleAnalytica\testing\testMessageBoxClass.py", line 16, in button_ok_clicked
    Messagebox.show_warning('TEST MESSAGE', title='TEST TITLE')
  File "C:\Users\Gamer\Documents\Projekte\coding\python\saleAnalytica\venvs\venv310\lib\site-packages\ttkbootstrap\dialogs\dialogs.py", line 1240, in show_warning
    dialog.show(position)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\saleAnalytica\venvs\venv310\lib\site-packages\ttkbootstrap\dialogs\dialogs.py", line 346, in show
    super().show(position)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\saleAnalytica\venvs\venv310\lib\site-packages\ttkbootstrap\dialogs\dialogs.py", line 71, in show
    self.build()
  File "C:\Users\Gamer\Documents\Projekte\coding\python\saleAnalytica\venvs\venv310\lib\site-packages\ttkbootstrap\dialogs\dialogs.py", line 125, in build
    self._toplevel = ttk.Toplevel(
  File "C:\Users\Gamer\Documents\Projekte\coding\python\saleAnalytica\venvs\venv310\lib\site-packages\ttkbootstrap\window.py", line 415, in __init__
    super().__init__(**kwargs)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\saleAnalytica\venvs\venv310\lib\site-packages\ttkbootstrap\style.py", line 5166, in __init__wrapper
    func(self, *args, **kwargs)
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 2653, in __init__
    self.title(root.title())
TypeError: 'str' object is not callable
```

### To Reproduce

I broke down my project to the possible root cause, my own inherited class.

```python
import ttkbootstrap as ttkk
from ttkbootstrap.dialogs.dialogs import Messagebox


class TestUi(ttkk.Window):
    def __init__(self, themename=""):
        super().__init__(themename=themename)

        self.title = 'Test Ui'
        self.geometry("400x300")

        self.button_ok = ttkk.Button(text='OK', command=self.button_ok_clicked)
        self.button_ok.pack()

    def button_ok_clicked(self):
        Messagebox.show_warning('TEST MESSAGE', title='TEST TITLE')


window = TestUi(themename="darkly")
window.mainloop()

```

### Expected behavior

A modal message box.

### Screenshots

![image](https://user-images.githubusercontent.com/901400/210481823-39feb51d-8f94-4ca6-b0af-5cf5a733b8d3.png)

### Additional context

While writing this BUG-Report I noticed that I set `self.title = 'a string'` **which is wrong** and always was wrong with vanilla `tkinter`, it just didn't threw an error.
```python
# WRONG:
self.title = "Test Ui"
```

It has to be:
```python
# CORRECT:
self.title("Test UI")
```

This wrong use also creates a main window with the wrong title `ttkbootstrap`.  
The Messagebox window gets the wrong title: `!toplevel` (which gets an incrementing number on each call, eg `!toplevel2`, `!toplevel3`,  ...)  

Since I am just trying out using ttkbootstrap instead of tkinter (as a drop-in replacement) in a small project I mostly re-used tkinter code.   

Leaving this bug report here for anyone googling for the error with a bit more description for the poor soul who might google for those.  
Also maybe this behavior is not intended, so leaving the decision to the maintainer ^^"

**Comment by israel-dryer** [comment]
Hi, I noticed the same issue with title, which is am method and not a property. Changing this results in the following: 
<img width="221" alt="image" src="https://user-images.githubusercontent.com/42584742/210487176-1852a554-4897-437b-aaae-c68787adc34c.png">

Just so you know, you can also set the title and size in the Window constructor; this makes it a bit simpler on creation. You would still need to use the legacy tk api for post-creation updates:
```python
window = Window(themename="darkly", title="Test UI", size=(400, 300))
```
