### ISSUE TITLE
I can't executable with ttkbootstrap library

### ISSUE THREAD

**Issue by kaomao1234** [israel-dryer/ttkbootstrap#43]

**Comment by kaomao1234** [comment]
[https://cdn.discordapp.com/attachments/698842872530731049/846776078886633553/unknown.png](url)

**Comment by israel-dryer** [comment]
can you be more specific about your issue? What code are you executing? What error message are you receiving?

**Comment by kaomao1234** [comment]
```py
Traceback (most recent call last):
"File ""importlib\resources .py"", line 97, in open_binary
FileNotFound Error: [Errno 2)No such file or directory
:  'C:\\Users\\Kaomao\\AppData\\Local\\Temp\\_MEI124362\\ttkbootstrap\\themes.json'
"During handling of the above exception, another exception occurred:"
Traceback (most recent call last):
File "Notepad.py", line 538, in <module>"
File "Notepad.py", line 20, in _init_
File "ttkbootstrap\_init_ .py" , line 57, ne _init_
File "ttkbootstrap\_init_ .py", line 75, in _load_themes
File "importlib\resources .py", line 139, in read text
File "importlib\resources .py", line 121, in open_text
File "importlib\resources .py", line 111, in open_binary
FileNotFound Error : 'themes.json' resource not found in 'ttkbootstrap '
(10520)Failed to execute script Notepad
```

**Comment by kaomao1234** [comment]
i covert py to exe but it can't run

**Comment by israel-dryer** [comment]
are you using pyinstaller?

**Comment by kaomao1234** [comment]
Yes

**Comment by kaomao1234** [comment]
This i use py2exe
`
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 741, in open_resource
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Notepad.py", line 539, in <module>
  File "Notepad.py", line 21, in __init__
  File "ttkbootstrap\__init__.pyc", line 80, in __init__
  File "ttkbootstrap\__init__.pyc", line 100, in _load_themes
  File "importlib\resources.pyc", line 139, in read_text
  File "importlib\resources.pyc", line 121, in open_text
  File "importlib\resources.pyc", line 91, in open_binary
  File "<frozen zipimport>", line 743, in open_resource
FileNotFoundError: ttkbootstrap/themes.json
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 741, in open_resource
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Notepad.py", line 539, in <module>
  File "Notepad.py", line 21, in __init__
  File "ttkbootstrap\__init__.pyc", line 80, in __init__
  File "ttkbootstrap\__init__.pyc", line 100, in _load_themes
  File "importlib\resources.pyc", line 139, in read_text
  File "importlib\resources.pyc", line 121, in open_text
  File "importlib\resources.pyc", line 91, in open_binary
  File "<frozen zipimport>", line 743, in open_resource
FileNotFoundError: ttkbootstrap/themes.json
`

**Comment by kaomao1234** [comment]
This i use py2exe
```py
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 741, in open_resource
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Notepad.py", line 539, in <module>
  File "Notepad.py", line 21, in __init__
  File "ttkbootstrap\__init__.pyc", line 80, in __init__
  File "ttkbootstrap\__init__.pyc", line 100, in _load_themes
  File "importlib\resources.pyc", line 139, in read_text
  File "importlib\resources.pyc", line 121, in open_text
  File "importlib\resources.pyc", line 91, in open_binary
  File "<frozen zipimport>", line 743, in open_resource
FileNotFoundError: ttkbootstrap/themes.json
```

**Comment by israel-dryer** [comment]
@kaomao1234 , Ok. I played around with this for a few minutes using pyinstaller and was able to get it to work. You need to add `--collect-all ttkbootstrap`

You can read more about this option here: https://pyinstaller.readthedocs.io/en/stable/usage.html

Essentially, what you need to do with either pyinstaller or py2exe is make sure that it is importing all of the required files. This can be done is various ways depending on how you are building your executable. I'm not sure if the method below is the most efficient, but it does work.

```console
C:\\> pyinstaller yourprogram.py --collect-all ttkbootstrap
```

**Comment by kaomao1234** [comment]
Thank you very much.

**Comment by israel-dryer** [comment]
@kaomao1234, did this fix your problem? If so, I'll close the issue.

**Comment by j-eltayar** [comment]
Hello, I included this:
`--collect-all ttkbootstrap`
in my pinstaller command and I still get the error

![image](https://user-images.githubusercontent.com/45185212/121195167-5e902f80-c83d-11eb-8cb9-8fd4a4255c9b.png)

and from what I can see ttkboostrap is in my package list 

![image](https://user-images.githubusercontent.com/45185212/121195332-81224880-c83d-11eb-8ce1-da00179ea1f0.png)

this also leads to ModuleNotFound errors when running through the anaconda terminal instead of the VS code terminal

as you can see error here

![image](https://user-images.githubusercontent.com/45185212/121195542-afa02380-c83d-11eb-87c8-55026b2640ac.png)

![image](https://user-images.githubusercontent.com/45185212/121195817-ee35de00-c83d-11eb-9567-6fb994caf1df.png)

no error here

**Comment by j-eltayar** [comment]
`pyinstaller main.spec --onedir --collect-all ttkbootstrap --hidden-import "heapq" --upx-dir C:\Users\dm3704\upx-3.96-win64 `

here the entire line i use to run pyinstaller

**Comment by israel-dryer** [comment]
are you able to post your spec file? Some of these options are flagged in the spec file as well. So, it may be that the CLI options are overriding spec file options, or vice versa.

**Comment by j-eltayar** [comment]
Thank you very much once I edited my spec file it ran like perfectly. They were, as you said overriding the commands in the commandline. As for my second issue with ModuleNotfoundError, I can bypass it by just using VScode to run the tkinter App instead of the anaconda terminal but do you have any thoughts on why anaconda's environment isn't reading the module even though it's downloaded and working?

Either way thank you ver much for the quick support and congratulations on the really awesome package, I've been really enjoying it!

**Comment by israel-dryer** [comment]
try running using the command `python main.py`.

**Comment by j-eltayar** [comment]
This also worked, thank you very much for your time.

**Comment by HamzaHassan99** [comment]
Try using the previous version of ttkbootstrap.Version 0.5.2 worked in my case.
