### ISSUE TITLE
FileNotFoundError : "themes.json" resource not found in "ttkboostrap'

### ISSUE THREAD

**Issue by Olawoledev** [israel-dryer/ttkbootstrap#45]
whenever i package an application using ttkbootstrap styles,it doesn't work

**Comment by israel-dryer** [comment]
Hi, check this issue: https://github.com/israel-dryer/ttkbootstrap/issues/43

**Comment by Olawoledev** [comment]
Working fine now

**Comment by WilliamNT** [comment]
same for me with py2exe.

```
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 741, in open_resource
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kvgen2.pyw", line 130, in <module>
  File "ttkbootstrap\__init__.pyc", line 80, in __init__
  File "ttkbootstrap\__init__.pyc", line 100, in _load_themes
  File "importlib\resources.pyc", line 139, in read_text
  File "importlib\resources.pyc", line 121, in open_text
  File "importlib\resources.pyc", line 91, in open_binary
  File "<frozen zipimport>", line 743, in open_resource
FileNotFoundError: ttkbootstrap/themes.json
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 741, in open_resource
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'ttkbootstrap\\themes.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kvgen2.pyw", line 130, in <module>
  File "ttkbootstrap\__init__.pyc", line 80, in __init__
  File "ttkbootstrap\__init__.pyc", line 100, in _load_themes
  File "importlib\resources.pyc", line 139, in read_text
  File "importlib\resources.pyc", line 121, in open_text
  File "importlib\resources.pyc", line 91, in open_binary
  File "<frozen zipimport>", line 743, in open_resource
FileNotFoundError: ttkbootstrap/themes.json
```

**Comment by israel-dryer** [comment]
@WilliamNT, did you check the issue I listed above? You'll need to make sure you include all the ttkbootstrap resources when you package your program. I've included some suggestions in https://github.com/israel-dryer/ttkbootstrap/issues/43

**Comment by exec85** [comment]
I tired all suggestions but for "py2exe" it doesn't seem to work.

Or does anyone know how to set the setup.py file for this?

Normally after compiling it is sufficient to just drag and drop all external files into the compiled folder, but not with the theme.json file.

this is how the py2exe setup file looks like:

setup(
    options={"py2exe": {"bundle_files": 1, "compressed": True}},
    windows=["main.py"],
    zipfile=None,
)
