### ISSUE TITLE
Error when detele a row in a filtered table

### ISSUE THREAD

**Issue by Tungsteno74** [israel-dryer/ttkbootstrap#457]
### Desktop (please complete the following information):

ttbootstrap 1.10.1
Window 11

### Describe the bug

The `self.iid` of the tableview class seems to be out of date when there is a filter applied and the reset button is clicked.

### To Reproduce

Use the default example of bootstrap:
```
import ttkbootstrap as ttk
from ttkbootstrap.tableview import Tableview
from ttkbootstrap.constants import *

app = ttk.Window(
    themename='superhero'
)
colors = app.style.colors

coldata = [
    {"text": "LicenseNumber", "stretch": True},
    "CompanyName",
    {"text": "UserCount", "stretch": True},
]

rowdata = [
    ('A123', 'IzzyCo', 12),
    ('A136', 'Kimdee Inc.', 45),
    ('A158', 'Farmadding Co.', 36)
]

dt = Tableview(
    master=app,
    coldata=coldata,
    rowdata=rowdata,
    paginated=True,
    searchable=True,
    bootstyle=INFO,
    # autofit=True,
    stripecolor=(colors.bg, None),
)

dt.pack(fill=BOTH, expand=YES, padx=10, pady=10)

app.mainloop()
```

filter the results for example with "arm" (use search box).
Then right-click on a row and in the showed menu click "delete selected rows".
Now click on the `reset table` button (bottom-right).

At this point the error shown below should appear.

### Expected behavior

When I click on the reset button, the search filter must be removed and all the rows of the updated table displayed (therefore without the previously deleted rows)

### Additional context

Traceback (most recent call last):
  File "C:\Program Files\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Virtualenvs\py38\LFREDeditorCTkinter-py38\lib\site-packages\ttkbootstrap\tableview.py", line 2049, in _search_table_data
    self.unload_table_data()
  File "D:\Virtualenvs\py38\LFREDeditorCTkinter-py38\lib\site-packages\ttkbootstrap\tableview.py", line 1023, in unload_table_data
    row.hide()
  File "D:\Virtualenvs\py38\LFREDeditorCTkinter-py38\lib\site-packages\ttkbootstrap\tableview.py", line 332, in hide
    self.view.detach(self.iid)
  File "C:\Program Files\Python\Python38\lib\tkinter\ttk.py", line 1255, in detach
    self.tk.call(self._w, "detach", items)
_tkinter.TclError: Item I003 not found

**Comment by TheDemonGuard** [comment]
I have made a pull request for a possible fix for this issue.
https://github.com/israel-dryer/ttkbootstrap/pull/665
