### ISSUE TITLE
The command `python3 -m ttkbootstrap` does not work to open Themes on mac OS

### ISSUE THREAD

**Issue by mas6y6** [israel-dryer/ttkbootstrap#477]
### Desktop (please complete the following information):

ttkbootstrap Version `v1.10.1`
Mac OS

### Describe the bug

I Have a issue when I open the `python3 -m ttkbootstrap` command

Command:
```
python3 -m ttkbootstrap
```

`python -m ttkbootstrap` does not work on my laptop

The error is in `Additional context` area

### To Reproduce

1. Run command
```
python3 -m ttkcreator
```
2. See Error
The Full error is in `Additional context` area

### Screenshots

<img width="550" alt="Screenshot 2023-08-10 at 8 46 21 PM" src="https://github.com/israel-dryer/ttkbootstrap/assets/125225333/fe4681cb-e57b-4701-ba6e-26a4c570ba5e">

### Additional context

The full traceback:
```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ttkcreator/__main__.py", line 471, in <module>
    creator = ThemeCreator()
              ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ttkcreator/__main__.py", line 23, in __init__
    self.demo_widgets = DemoWidgets(self, self.style)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ttkcreator/__main__.py", line 245, in __init__
    self.create_left_frame()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ttkcreator/__main__.py", line 445, in create_left_frame
    m = ttk.Meter(
        ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ttkbootstrap/widgets.py", line 718, in __init__
    self._setup_widget()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ttkbootstrap/widgets.py", line 759, in _setup_widget
    self._draw_meter()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ttkbootstrap/widgets.py", line 856, in _draw_meter
    img.resize((self._metersize, self._metersize), Image.CUBIC)
                                                   ^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?
```

**Comment by wrogner** [comment]
Search for the widgets.py file (if installed in a venv, venv/lib/<python3.xx>/site-packages/ttkbootstrap/widgets.py)
and replace it with this version:
[widgets.py.zip](https://github.com/israel-dryer/ttkbootstrap/files/12386601/widgets.py.zip)

**Comment by mas6y6** [comment]
Ok lets see if this works

**Comment by mas6y6** [comment]
Its was fixed

**Comment by wrogner** [comment]
I provided a workaround (and of course this works).

However, the problem is not fixed as long as the installation packages are not updated (people still pip install ttkbootstrap and get broken libraries).

I cannot help with the last step.
