### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by Zephyruss1** [israel-dryer/ttkbootstrap#534]
### Desktop (please complete the following information):

ttkbootstrap==1.10.1
OS: Windows 11

### Describe the bug

Basiclly when im trying to run my main.py file receiving error:
I think there is a bug about **encoding**.

`Traceback (most recent call last):
  File "c:\Users\ekber\OneDrive\Masaüstü\Desktop_brightness_app_github\main.py", line 13, in <module>
    import ttkbootstrap as tb`

  `File "C:\Users\ekber\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\__init__.py", line 3, in <module>
    from ttkbootstrap.widgets import *`

  `File "C:\Users\ekber\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 14, in <module>
    from ttkbootstrap.dialogs import Querybox`

  `File "C:\Users\ekber\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\dialogs\__init__.py", line 1, in <module>
    from ttkbootstrap.dialogs.dialogs import *`

 `File "C:\Users\ekber\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\dialogs\dialogs.py", line 536, in <module>
    class DatePickerDialog:
  File "C:\Users\ekber\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\dialogs\dialogs.py", line 566, in DatePickerDialog
    locale.setlocale(locale.LC_ALL, locale.setlocale(locale.LC_TIME, ""))`

  `File "C:\Users\ekber\AppData\Local\Programs\Python\Python311\Lib\locale.py", line 627, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`locale.Error: unsupported locale setting`

### Expected behavior

**main.py** file expected run without error

### Additional context
I've heard **locale.Error** is can receiveable in _Linux_ opeartion systems.

If want to inspect all of the code what i did: **https://github.com/Zephyruss1/Desktop-Brightness**

**Comment by Zephyruss1** [comment]
I closed issue with due duplicate. This [issue link](https://github.com/israel-dryer/ttkbootstrap/issues/505) worked for me.
