### ISSUE TITLE
ttkbootstrap dosen't like tkinter Label, Button.....

### ISSUE THREAD

**Issue by AlexiJemano** [israel-dryer/ttkbootstrap#540]
### Desktop (please complete the following information):

Traceback (most recent call last):
  File "PROJECT DIRECTORY", line 8, in <module>
    import ttkbootstrap as ttk
  File "PROJECT DIRECTORY", line 132, in <module>
    Title = ttk.Label(master=root, text="Truth or Dare!", font="Courier 24")
            ^^^^^^^^^
AttributeError: partially initialized module 'ttkbootstrap' has no attribute 'Label' (most likely due to a circular import)

### Describe the bug

My tkinter program works fine but when I try to import ttkbootstrap it breaks. It says that .Label, .Button are not defined in the ttkbootstrap code file

**Comment by jdsayle** [comment]
Hi @AlexiJemano,

Can you share the imports section from your code? The AttributeError: partially initialized module, you are getting sounds quite similar to this issue from SO: https://stackoverflow.com/questions/59762996/how-to-fix-attributeerror-partially-initialized-module
