### ISSUE TITLE
ttk bootrap not working properly

### ISSUE THREAD

**Issue by mayur533** [israel-dryer/ttkbootstrap#545]
ttkboottrap versionn 1.10.1

python3 todolist.py
Traceback (most recent call last):
  File "/home/mayur/Mayur/Python/Codsoft Intership/Tasks/Task1 To-Do list/todolist.py", line 2, in <module>
    import ttkbootstrap as ttk
  File "/home/mayur/.local/lib/python3.11/site-packages/ttkbootstrap/__init__.py", line 1, in <module>
    from ttkbootstrap.style import Style
  File "/home/mayur/.local/lib/python3.11/site-packages/ttkbootstrap/style.py", line 9, in <module>
    from PIL import ImageTk, ImageDraw, Image, ImageFont
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by rdbende** [comment]
https://stackoverflow.com/a/48170806

**Comment by mayur533** [comment]
Hi there sorry for late reply but if you're not able to use ttk bootstrap 
I would like to know which os you are using

**Comment by rdbende** [comment]
Me? I thought you're one who isn't able to use ttkbootstrap.

I'm using Fedora btw
