### ISSUE TITLE
Python 3.11 errors out on using Meter

### ISSUE THREAD

**Issue by itguy217** [israel-dryer/ttkbootstrap#563]
### Desktop (please complete the following information):

ttkbootstrap 1.10.1

### Describe the bug

Traceback (most recent call last):
  File "C:\Users\raadmin\Documents\weather.py", line 34, in <module>
    tempMeter = tb.Meter(root, bootstyle="info",subtextstyle="danger", subtext="Current Temp")
  File "C:\Users\raadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 718, in __init__
    self._setup_widget()
  File "C:\Users\raadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 759, in _setup_widget
    self._draw_meter()
  File "C:\Users\raadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 856, in _draw_meter
    img.resize((self._metersize, self._metersize), Image.CUBIC)
AttributeError: module 'PIL.Image' has no attribute 'CUBIC'. Did you mean: 'BICUBIC'?
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\raadmin\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\raadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 954, in _on_theme_change
    self._draw_meter()
  File "C:\Users\raadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ttkbootstrap\widgets.py", line 856, in _draw_meter
    img.resize((self._metersize, self._metersize), Image.CUBIC)
                                                   ^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'CUBIC'

### To Reproduce

Have python 3.11 installed.
pip install ttkbootstrap or python -m pip install ttkbootstrap

Run the following code:
create a ttk window and add the following:
# Create a meter to visually represent the temperature
tempMeter = tb.Meter(root, bootstyle="info",subtextstyle="danger", subtext="Current Temp")
tempMeter.pack(pady=30)

### Expected behavior

Should see a Meter with a number and a visual representation.

**Comment by itguy217** [comment]
Windows 11 Pro

**Comment by EVA-JianJun** [comment]
As the attribute Image.CUBIC is deprecated (replaced by Image.BICUBIC) and removed in Pillow v10.0.0. Either install an older version (v9.5.0) of Pillow module or create the attribute explicitly before importing ttkbootstrap module:
```
from PIL import Image
Image.CUBIC = Image.BICUBIC
import ttkbootstrap as ttk
...
```
https://stackoverflow.com/questions/76717279/ttkbootstrap-meter-widget-doc-example-not-working

but this is realy a bug.
