### ISSUE TITLE
_tkinter.TclError: couldn't recognize image data

### ISSUE THREAD

**Issue by QingyuFeng** [israel-dryer/ttkbootstrap#584]
### Desktop (please complete the following information):

ttkbootstrap version: 1.10.1
OS: Macos sonoma 14.5
python version: 3.9.6

### Describe the bug

I was trying to develop an app with ttkbootstrap. However, when I was testing the package, it worked pretty on windows 10. But, when I was trying it on Macos, an error occurred. I created a virtual environment using the Macos default python version, and try to run the text reader demo (https://ttkbootstrap.readthedocs.io/en/latest/gallery/textreader/), it is not working. I checked online and found it was a common error with PhotoImage.

### To Reproduce

DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "/Users/fengqingyu/Documents/appDevMaster/emc_ecoevalt/src/test_notebook.py", line 47, in <module>
    app = ttk.Window("Text Reader", "sandstone")
  File "/Users/fengqingyu/Documents/appDevMaster/emc_ecoevalt/env/lib/python3.9/site-packages/ttkbootstrap/window.py", line 231, in __init__
    self._icon = tkinter.PhotoImage(master=self, data=Icon.icon)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize image data

**Comment by 1337haxx0r** [comment]
Yup, same issue here.
Possibly any solutions?

**Comment by rdbende** [comment]
The version of tkinter provided in macOS is probably outdated. If the following code:

```python
import tkinter
print(tkinter.TkVersion)
```
gives anything below `8.6`, you should update it somehow. There instructions on it on the internet.

**Comment by 1337haxx0r** [comment]
> The version of tkinter provided in macOS is probably outdated. If the following code:
> 
> ```python
> import tkinter
> print(tkinter.TkVersion)
> ```
> 
> gives anything below `8.6`, you should update it somehow. There instructions on it on the internet.

Appreciate your response. indeed, it is 8.5. I'll work on updating it

**Comment by 1337haxx0r** [comment]
Alright.
So I did update tkinter to 8.6 following this answer: [https://stackoverflow.com/a/61879759](https://stackoverflow.com/a/61879759)

**_Done these steps:_**

```bash
brew install tcl-tk
```

```bash
export PATH="/usr/local/opt/tcl-tk/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"
export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"
export PKG_CONFIG_PATH="/usr/local/opt/tcl-tk/lib/pkgconfig"
```

```bash
brew reinstall python
```

make sure version is updated: 
```bash
brew info tcl-tk
```


**_Then created new environment_**

```bash
python3 -m venv myenv
```

Activate it
```bash
source myenv/bin/activate
```

and run the *.py test file with:

```python
import tkinter
print(tkinter.TkVersion)
```

So, I moved my projects files into the new environment and issue with not recognizing image data was solved.
Tank you @rdbende for guiding the path =)
