### ISSUE TITLE
ttkcreator don’t work

### ISSUE THREAD

**Issue by Alden68** [israel-dryer/ttkbootstrap#598]
### Desktop (please complete the following information):

Ttkboostrap : 1.10.1
Windows 7

### Describe the bug

PS C:\Users\alden> py -m ttkcreator
Traceback (most recent call last):
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkcreator\__main__.py", line 471, in <m
odule>
    creator = ThemeCreator()
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkcreator\__main__.py", line 23, in __i
nit__
    self.demo_widgets = DemoWidgets(self, self.style)
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkcreator\__main__.py", line 245, in __
init__
    self.create_left_frame()
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkcreator\__main__.py", line 445, in cr
eate_left_frame
    m = ttk.Meter(
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkbootstrap\widgets.py", line 718, in _
_init__
    self._setup_widget()
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkbootstrap\widgets.py", line 759, in _
setup_widget
    self._draw_meter()
  File "C:\Users\alden\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkbootstrap\widgets.py", line 856, in _
draw_meter
    img.resize((self._metersize, self._metersize), Image.CUBIC)
AttributeError: module 'PIL.Image' has no attribute 'CUBIC'
PS C:\Users\alden>

### To Reproduce

Python -m ttkcreator

### Expected behavior

ttkcreator must work

**Comment by nebhead** [comment]
Seeing the same issue here with Python 3.12

Package           Version
----------------- ------------
pillow            10.4.0
pip               24.0
pygame            2.6.0
pypng             0.20220715.0
qrcode            7.4.2
ttkbootstrap      1.10.1
typing_extensions 4.12.2

**Comment by fire-eggs** [comment]
See issue #566

**Comment by gtgor** [comment]
https://github.com/israel-dryer/ttkbootstrap/issues/566

**Comment by israel-dryer** [comment]
fixed with #490
