### ISSUE TITLE
mkdocstring consistently fails to build api docs for readthedocs

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/ttkbootstrap#81]
```
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/ttkbootstrap/checkouts/latest/_build/html
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
[33mWARNING  -  [0mDocumentation file 'index.md' contains a link to '../assets/themes/themes.gif' which is not found in the documentation files.
[31mERROR    -  [0mmkdocstrings.extension: Importing 'ttkbootstrap.utility' failed, possible causes are:
- an exception happened while importing
- an element in the path does not exist
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ttkbootstrap/envs/latest/lib/python3.9/site-packages/pytkdocs/loader.py", line 264, in get_object_tree
    parent_module = importlib.import_module(parent_module_path)
  File "/home/docs/.asdf/installs/python/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ttkbootstrap'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ttkbootstrap/envs/latest/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
    output = json.dumps(process_json(line))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ttkbootstrap/envs/latest/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
    return process_config(json.loads(json_input))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ttkbootstrap/envs/latest/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ttkbootstrap/envs/latest/lib/python3.9/site-packages/pytkdocs/loader.py", line 355, in get_object_documentation
    leaf = get_object_tree(dotted_path, self.new_path_syntax)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ttkbootstrap/envs/latest/lib/python3.9/site-packages/pytkdocs/loader.py", line 267, in get_object_tree
    raise ImportError(
ImportError: Importing 'ttkbootstrap.utility' failed, possible causes are:
- an exception happened while importing
- an element in the path does not exist

[31mERROR    -  [0mError reading page 'api/utility.md':
[31mERROR    -  [0mCould not collect 'ttkbootstrap.utility'

Aborted with a BuildError!
```

**Comment by israel-dryer** [comment]
fixed this by adding the setup command to find the source

```yaml
plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
              setup_commands:
                - import sys
                - sys.path.append("src")
```
