### ISSUE TITLE
Unable to load custom theme

### ISSUE THREAD

**Issue by whmsft** [israel-dryer/ttkbootstrap#92]
I have a theme named `monokai-aora`, in the last updates to ttkbootstrap, i have used it without any troubles..

But now with the latest version on Pypi, this error happens:
```
Traceback (most recent call last):
  File "E:\Programming\WhirlEdit\WhirlEdit\main.py", line 735, in <module>
    thisroot = ttkbootstrap.Style(theme = 'monokai-aora',themes_file=theme_file).master
  File "E:\programming\Python38-32\lib\site-packages\ttkbootstrap\__init__.py", line 81, in __init__
    self._load_themes(themes_file)
  File "E:\programming\Python38-32\lib\site-packages\ttkbootstrap\__init__.py", line 119, in _load_themes
    themetype=settings['type'],
TypeError: list indices must be integers or slices, not str
```

the themefile (`monokai-aora.json`):
```json
{
	"themes": [
		{
			"name": "monokai-aora",
			"font": "Helvetica 10",
			"type": "dark",
			"colors": {
				"primary": "#528bff",
				"secondary": "#0F1419",
				"success": "#81F900",
				"info": "#528bff",
				"warning": "#FF9700",
				"danger": "#c24038",
				"bg": "#0F1419",
				"fg": "#f8f8f0",
				"selectbg": "#444444",
				"selectfg": "#f8f8f0",
				"border": "#222222",
				"inputfg": "#f8f8f0",
				"inputbg": "#1d1f23"
			}
		}
	]
}
```

Do the new version include anything i am not aware of?

**Comment by israel-dryer** [comment]
Yes. 1.0 is a complete rebuild. I removed to dependence on JSON files because people were having compile issues. So it is now in a py file. You should still be able to use this theme with a few adjustments.

You can see what that looks like here.

https://ttkbootstrap.readthedocs.io/en/latest/themes/themecreator/#import-user-themes

**Comment by whmsft** [comment]
Now i tried again but this happened:
```
Traceback (most recent call last):
  File "E:\programming\whirledit\whirledit\main.py", line 735, in <module>
    thisroot = ttkbootstrap.Style(theme = 'wm10',themes_file=theme_file).master
  File "E:\programming\Python38-32\lib\site-packages\ttkbootstrap\__init__.py", line 81, in __init__
    self._load_themes(themes_file)
  File "E:\programming\Python38-32\lib\site-packages\ttkbootstrap\__init__.py", line 106, in _load_themes
    user_themes = json.load(f)
  File "E:\programming\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "E:\programming\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "E:\programming\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\programming\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

my theme_file `wm10.py`:
```
USER_THEMES={
        'wm10': {
            'type': 'dark',
            'colors': {
                'primary': '#0084ff',
                'secondary': '#202020',
                'success': '#77b300',
                'info': '#9933cc',
                'warning': '#ff8800',
                'danger': '#cc0000',
                'bg': '#000000',
                'fg': '#ffffff',
                'selectbg': '#101010',
                'selectfg': '#ffffff',
                'border': '#000000',
                'inputfg': '#ffffff',
                'inputbg': '#000000',
                'light': '#ffffff',
                'dark': '#000000'
                }
            }
        }
```

and i wrote this theme using ttkcreator

**Comment by israel-dryer** [comment]
@whmsft, oh ok. I didn't realize I still had the json importer in there...If you created the theme using the ttkcreator and clicked the "save" button, it should already be available in your application. And, if you import the file with ttkcreator, it should be in the application as well.

However, you can still technically use the json importer, however, it would need to be in the following format.

```json
{
    "wm10": {
        "type": "dark",
        "colors": {
            "primary": "#0084ff",
            "secondary": "#202020",
            "success": "#77b300",
            "info": "#9933cc",
            "warning": "#ff8800",
            "danger": "#cc0000",
            "bg": "#000000",
            "fg": "#ffffff",
            "selectbg": "#101010",
            "selectfg": "#ffffff",
            "border": "#000000",
            "inputfg": "#ffffff",
            "inputbg": "#000000",
            "light": "#ffffff",
            "dark": "#000000"
        }
    }
}
```

Let me know if this fixes the issue. If you created it or imported it with ttkcreator, you should be able to use the theme with no file links. But, as I mentioned, you can import the json as well as long as it's in JSON format.

Let me know if this works.
